[package]
name = "feap_macro_utils"
version.workspace = true
edition.workspace = true

[dependencies]
syn = "2.0"
quote = "1.0"
toml_edit = { version = "0.23.2", default-features = false, features = [
    "parse",
] }
