[package]
name = "feap_app"
version.workspace = true
edition.workspace = true

[features]
trace = ["dep:tracing"]

[dependencies]
tracing = {workspace = true, optional=true}

downcast-rs = {workspace = true}
